// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: alert.proto

package alert

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Params struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FabricName    string                 `protobuf:"bytes,1,opt,name=fabricName,proto3" json:"fabricName,omitempty"`
	NodeName      string                 `protobuf:"bytes,2,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	AnomalyType   string                 `protobuf:"bytes,3,opt,name=anomalyType,proto3" json:"anomalyType,omitempty"`
	StartTs       string                 `protobuf:"bytes,4,opt,name=startTs,proto3" json:"startTs,omitempty"`
	EndTs         string                 `protobuf:"bytes,5,opt,name=endTs,proto3" json:"endTs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Params) Reset() {
	*x = Params{}
	mi := &file_alert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Params) ProtoMessage() {}

func (x *Params) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Params.ProtoReflect.Descriptor instead.
func (*Params) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{0}
}

func (x *Params) GetFabricName() string {
	if x != nil {
		return x.FabricName
	}
	return ""
}

func (x *Params) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *Params) GetAnomalyType() string {
	if x != nil {
		return x.AnomalyType
	}
	return ""
}

func (x *Params) GetStartTs() string {
	if x != nil {
		return x.StartTs
	}
	return ""
}

func (x *Params) GetEndTs() string {
	if x != nil {
		return x.EndTs
	}
	return ""
}

type AffectedEp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	EndpointCount int32                  `protobuf:"varint,2,opt,name=endpointCount,proto3" json:"endpointCount,omitempty"`
	Params        *Params                `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AffectedEp) Reset() {
	*x = AffectedEp{}
	mi := &file_alert_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AffectedEp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AffectedEp) ProtoMessage() {}

func (x *AffectedEp) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AffectedEp.ProtoReflect.Descriptor instead.
func (*AffectedEp) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{1}
}

func (x *AffectedEp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AffectedEp) GetEndpointCount() int32 {
	if x != nil {
		return x.EndpointCount
	}
	return 0
}

func (x *AffectedEp) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

type Adjacency struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PeerDeviceName    string                 `protobuf:"bytes,1,opt,name=peerDeviceName,proto3" json:"peerDeviceName,omitempty"`
	PeerInterfaceName string                 `protobuf:"bytes,2,opt,name=peerInterfaceName,proto3" json:"peerInterfaceName,omitempty"`
	ModTs             string                 `protobuf:"bytes,3,opt,name=modTs,proto3" json:"modTs,omitempty"`
	FabricName        string                 `protobuf:"bytes,4,opt,name=fabricName,proto3" json:"fabricName,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Adjacency) Reset() {
	*x = Adjacency{}
	mi := &file_alert_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Adjacency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Adjacency) ProtoMessage() {}

func (x *Adjacency) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Adjacency.ProtoReflect.Descriptor instead.
func (*Adjacency) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{2}
}

func (x *Adjacency) GetPeerDeviceName() string {
	if x != nil {
		return x.PeerDeviceName
	}
	return ""
}

func (x *Adjacency) GetPeerInterfaceName() string {
	if x != nil {
		return x.PeerInterfaceName
	}
	return ""
}

func (x *Adjacency) GetModTs() string {
	if x != nil {
		return x.ModTs
	}
	return ""
}

func (x *Adjacency) GetFabricName() string {
	if x != nil {
		return x.FabricName
	}
	return ""
}

type VpcNode struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeName          string                 `protobuf:"bytes,1,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	Interface         string                 `protobuf:"bytes,2,opt,name=interface,proto3" json:"interface,omitempty"`
	PcId              string                 `protobuf:"bytes,3,opt,name=pcId,proto3" json:"pcId,omitempty"`
	VpcOperSt         string                 `protobuf:"bytes,4,opt,name=vpcOperSt,proto3" json:"vpcOperSt,omitempty"`
	PcOperStateQual   string                 `protobuf:"bytes,5,opt,name=pcOperStateQual,proto3" json:"pcOperStateQual,omitempty"`
	InterfaceType     string                 `protobuf:"bytes,6,opt,name=interfaceType,proto3" json:"interfaceType,omitempty"`
	InterfaceUniqueId string                 `protobuf:"bytes,7,opt,name=interfaceUniqueId,proto3" json:"interfaceUniqueId,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VpcNode) Reset() {
	*x = VpcNode{}
	mi := &file_alert_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VpcNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VpcNode) ProtoMessage() {}

func (x *VpcNode) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VpcNode.ProtoReflect.Descriptor instead.
func (*VpcNode) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{3}
}

func (x *VpcNode) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *VpcNode) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *VpcNode) GetPcId() string {
	if x != nil {
		return x.PcId
	}
	return ""
}

func (x *VpcNode) GetVpcOperSt() string {
	if x != nil {
		return x.VpcOperSt
	}
	return ""
}

func (x *VpcNode) GetPcOperStateQual() string {
	if x != nil {
		return x.PcOperStateQual
	}
	return ""
}

func (x *VpcNode) GetInterfaceType() string {
	if x != nil {
		return x.InterfaceType
	}
	return ""
}

func (x *VpcNode) GetInterfaceUniqueId() string {
	if x != nil {
		return x.InterfaceUniqueId
	}
	return ""
}

type Pc struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ConfiguredMemberList []string               `protobuf:"bytes,1,rep,name=configuredMemberList,proto3" json:"configuredMemberList,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Pc) Reset() {
	*x = Pc{}
	mi := &file_alert_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pc) ProtoMessage() {}

func (x *Pc) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pc.ProtoReflect.Descriptor instead.
func (*Pc) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{4}
}

func (x *Pc) GetConfiguredMemberList() []string {
	if x != nil {
		return x.ConfiguredMemberList
	}
	return nil
}

type Vpc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DomainId      string                 `protobuf:"bytes,1,opt,name=domainId,proto3" json:"domainId,omitempty"`
	NodeList      []*VpcNode             `protobuf:"bytes,2,rep,name=nodeList,proto3" json:"nodeList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vpc) Reset() {
	*x = Vpc{}
	mi := &file_alert_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vpc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vpc) ProtoMessage() {}

func (x *Vpc) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vpc.ProtoReflect.Descriptor instead.
func (*Vpc) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{5}
}

func (x *Vpc) GetDomainId() string {
	if x != nil {
		return x.DomainId
	}
	return ""
}

func (x *Vpc) GetNodeList() []*VpcNode {
	if x != nil {
		return x.NodeList
	}
	return nil
}

type Bgp struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConnIf           string                 `protobuf:"bytes,1,opt,name=connIf,proto3" json:"connIf,omitempty"`
	BgpType          string                 `protobuf:"bytes,2,opt,name=bgpType,proto3" json:"bgpType,omitempty"`
	PrefixChangeType string                 `protobuf:"bytes,3,opt,name=prefixChangeType,proto3" json:"prefixChangeType,omitempty"`
	PeerIp           string                 `protobuf:"bytes,4,opt,name=peerIp,proto3" json:"peerIp,omitempty"`
	Vrf              string                 `protobuf:"bytes,5,opt,name=vrf,proto3" json:"vrf,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Bgp) Reset() {
	*x = Bgp{}
	mi := &file_alert_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bgp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bgp) ProtoMessage() {}

func (x *Bgp) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bgp.ProtoReflect.Descriptor instead.
func (*Bgp) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{6}
}

func (x *Bgp) GetConnIf() string {
	if x != nil {
		return x.ConnIf
	}
	return ""
}

func (x *Bgp) GetBgpType() string {
	if x != nil {
		return x.BgpType
	}
	return ""
}

func (x *Bgp) GetPrefixChangeType() string {
	if x != nil {
		return x.PrefixChangeType
	}
	return ""
}

func (x *Bgp) GetPeerIp() string {
	if x != nil {
		return x.PeerIp
	}
	return ""
}

func (x *Bgp) GetVrf() string {
	if x != nil {
		return x.Vrf
	}
	return ""
}

type Ospf struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	InterfaceNameFromDN string                 `protobuf:"bytes,1,opt,name=interfaceNameFromDN,proto3" json:"interfaceNameFromDN,omitempty"`
	DerivedIntf         string                 `protobuf:"bytes,2,opt,name=derivedIntf,proto3" json:"derivedIntf,omitempty"`
	PeerIp              string                 `protobuf:"bytes,3,opt,name=peerIp,proto3" json:"peerIp,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Ospf) Reset() {
	*x = Ospf{}
	mi := &file_alert_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ospf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ospf) ProtoMessage() {}

func (x *Ospf) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ospf.ProtoReflect.Descriptor instead.
func (*Ospf) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{7}
}

func (x *Ospf) GetInterfaceNameFromDN() string {
	if x != nil {
		return x.InterfaceNameFromDN
	}
	return ""
}

func (x *Ospf) GetDerivedIntf() string {
	if x != nil {
		return x.DerivedIntf
	}
	return ""
}

func (x *Ospf) GetPeerIp() string {
	if x != nil {
		return x.PeerIp
	}
	return ""
}

type Svi struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AssociatedInterface string                 `protobuf:"bytes,1,opt,name=associatedInterface,proto3" json:"associatedInterface,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Svi) Reset() {
	*x = Svi{}
	mi := &file_alert_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Svi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Svi) ProtoMessage() {}

func (x *Svi) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Svi.ProtoReflect.Descriptor instead.
func (*Svi) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{8}
}

func (x *Svi) GetAssociatedInterface() string {
	if x != nil {
		return x.AssociatedInterface
	}
	return ""
}

type CustomEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomEvent) Reset() {
	*x = CustomEvent{}
	mi := &file_alert_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomEvent) ProtoMessage() {}

func (x *CustomEvent) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomEvent.ProtoReflect.Descriptor instead.
func (*CustomEvent) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{9}
}

func (x *CustomEvent) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CustomEvent) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type ApicFault struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	ConfigQuals   []string               `protobuf:"bytes,2,rep,name=configQuals,proto3" json:"configQuals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApicFault) Reset() {
	*x = ApicFault{}
	mi := &file_alert_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApicFault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApicFault) ProtoMessage() {}

func (x *ApicFault) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApicFault.ProtoReflect.Descriptor instead.
func (*ApicFault) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{10}
}

func (x *ApicFault) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ApicFault) GetConfigQuals() []string {
	if x != nil {
		return x.ConfigQuals
	}
	return nil
}

type CustomData struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ControllerName     string                 `protobuf:"bytes,1,opt,name=controllerName,proto3" json:"controllerName,omitempty"`
	AccountName        string                 `protobuf:"bytes,2,opt,name=accountName,proto3" json:"accountName,omitempty"`
	ApplicationName    string                 `protobuf:"bytes,3,opt,name=applicationName,proto3" json:"applicationName,omitempty"`
	TierName           string                 `protobuf:"bytes,4,opt,name=tierName,proto3" json:"tierName,omitempty"`
	NodeName           string                 `protobuf:"bytes,5,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	HealthRuleName     string                 `protobuf:"bytes,6,opt,name=healthRuleName,proto3" json:"healthRuleName,omitempty"`
	VrfDip             string                 `protobuf:"bytes,7,opt,name=vrfDip,proto3" json:"vrfDip,omitempty"`
	AffectedEp         *AffectedEp            `protobuf:"bytes,8,opt,name=affectedEp,proto3" json:"affectedEp,omitempty"`
	Endpoints          []string               `protobuf:"bytes,9,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	HostName           string                 `protobuf:"bytes,10,opt,name=hostName,proto3" json:"hostName,omitempty"`
	VmName             string                 `protobuf:"bytes,11,opt,name=vmName,proto3" json:"vmName,omitempty"`
	NetworkName        string                 `protobuf:"bytes,12,opt,name=networkName,proto3" json:"networkName,omitempty"`
	DsName             string                 `protobuf:"bytes,13,opt,name=dsName,proto3" json:"dsName,omitempty"`
	DeviceName         string                 `protobuf:"bytes,14,opt,name=deviceName,proto3" json:"deviceName,omitempty"`
	MoveCount          int32                  `protobuf:"varint,15,opt,name=moveCount,proto3" json:"moveCount,omitempty"`
	Interfaces         string                 `protobuf:"bytes,16,opt,name=interfaces,proto3" json:"interfaces,omitempty"`
	Events             []*CustomEvent         `protobuf:"bytes,17,rep,name=events,proto3" json:"events,omitempty"`
	Adjacency          *Adjacency             `protobuf:"bytes,18,opt,name=adjacency,proto3" json:"adjacency,omitempty"`
	Vpc                *Vpc                   `protobuf:"bytes,19,opt,name=vpc,proto3" json:"vpc,omitempty"`
	Pc                 *Pc                    `protobuf:"bytes,20,opt,name=pc,proto3" json:"pc,omitempty"`
	Bgp                *Bgp                   `protobuf:"bytes,21,opt,name=bgp,proto3" json:"bgp,omitempty"`
	PcId               string                 `protobuf:"bytes,22,opt,name=pcId,proto3" json:"pcId,omitempty"`
	Ospf               *Ospf                  `protobuf:"bytes,23,opt,name=ospf,proto3" json:"ospf,omitempty"`
	Svi                *Svi                   `protobuf:"bytes,24,opt,name=svi,proto3" json:"svi,omitempty"`
	RcaData            string                 `protobuf:"bytes,25,opt,name=rcaData,proto3" json:"rcaData,omitempty"`
	ApicFault          *ApicFault             `protobuf:"bytes,26,opt,name=apicFault,proto3" json:"apicFault,omitempty"`
	ImpactResourceType string                 `protobuf:"bytes,27,opt,name=impactResourceType,proto3" json:"impactResourceType,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CustomData) Reset() {
	*x = CustomData{}
	mi := &file_alert_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomData) ProtoMessage() {}

func (x *CustomData) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomData.ProtoReflect.Descriptor instead.
func (*CustomData) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{11}
}

func (x *CustomData) GetControllerName() string {
	if x != nil {
		return x.ControllerName
	}
	return ""
}

func (x *CustomData) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *CustomData) GetApplicationName() string {
	if x != nil {
		return x.ApplicationName
	}
	return ""
}

func (x *CustomData) GetTierName() string {
	if x != nil {
		return x.TierName
	}
	return ""
}

func (x *CustomData) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *CustomData) GetHealthRuleName() string {
	if x != nil {
		return x.HealthRuleName
	}
	return ""
}

func (x *CustomData) GetVrfDip() string {
	if x != nil {
		return x.VrfDip
	}
	return ""
}

func (x *CustomData) GetAffectedEp() *AffectedEp {
	if x != nil {
		return x.AffectedEp
	}
	return nil
}

func (x *CustomData) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *CustomData) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *CustomData) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

func (x *CustomData) GetNetworkName() string {
	if x != nil {
		return x.NetworkName
	}
	return ""
}

func (x *CustomData) GetDsName() string {
	if x != nil {
		return x.DsName
	}
	return ""
}

func (x *CustomData) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *CustomData) GetMoveCount() int32 {
	if x != nil {
		return x.MoveCount
	}
	return 0
}

func (x *CustomData) GetInterfaces() string {
	if x != nil {
		return x.Interfaces
	}
	return ""
}

func (x *CustomData) GetEvents() []*CustomEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *CustomData) GetAdjacency() *Adjacency {
	if x != nil {
		return x.Adjacency
	}
	return nil
}

func (x *CustomData) GetVpc() *Vpc {
	if x != nil {
		return x.Vpc
	}
	return nil
}

func (x *CustomData) GetPc() *Pc {
	if x != nil {
		return x.Pc
	}
	return nil
}

func (x *CustomData) GetBgp() *Bgp {
	if x != nil {
		return x.Bgp
	}
	return nil
}

func (x *CustomData) GetPcId() string {
	if x != nil {
		return x.PcId
	}
	return ""
}

func (x *CustomData) GetOspf() *Ospf {
	if x != nil {
		return x.Ospf
	}
	return nil
}

func (x *CustomData) GetSvi() *Svi {
	if x != nil {
		return x.Svi
	}
	return nil
}

func (x *CustomData) GetRcaData() string {
	if x != nil {
		return x.RcaData
	}
	return ""
}

func (x *CustomData) GetApicFault() *ApicFault {
	if x != nil {
		return x.ApicFault
	}
	return nil
}

func (x *CustomData) GetImpactResourceType() string {
	if x != nil {
		return x.ImpactResourceType
	}
	return ""
}

type EntityNameList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectType    string                 `protobuf:"bytes,1,opt,name=objectType,proto3" json:"objectType,omitempty"`
	ObjectValue   []string               `protobuf:"bytes,2,rep,name=objectValue,proto3" json:"objectValue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityNameList) Reset() {
	*x = EntityNameList{}
	mi := &file_alert_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityNameList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityNameList) ProtoMessage() {}

func (x *EntityNameList) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityNameList.ProtoReflect.Descriptor instead.
func (*EntityNameList) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{12}
}

func (x *EntityNameList) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *EntityNameList) GetObjectValue() []string {
	if x != nil {
		return x.ObjectValue
	}
	return nil
}

type AnomalyObjectsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Identifier    string                 `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,4,opt,name=isPrimary,proto3" json:"isPrimary,omitempty"`
	IsHealthy     bool                   `protobuf:"varint,5,opt,name=isHealthy,proto3" json:"isHealthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnomalyObjectsList) Reset() {
	*x = AnomalyObjectsList{}
	mi := &file_alert_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnomalyObjectsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnomalyObjectsList) ProtoMessage() {}

func (x *AnomalyObjectsList) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnomalyObjectsList.ProtoReflect.Descriptor instead.
func (*AnomalyObjectsList) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{13}
}

func (x *AnomalyObjectsList) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AnomalyObjectsList) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *AnomalyObjectsList) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AnomalyObjectsList) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *AnomalyObjectsList) GetIsHealthy() bool {
	if x != nil {
		return x.IsHealthy
	}
	return false
}

type Alert struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	StartTs                  string                 `protobuf:"bytes,1,opt,name=startTs,proto3" json:"startTs,omitempty"`
	EndTs                    string                 `protobuf:"bytes,2,opt,name=endTs,proto3" json:"endTs,omitempty"`
	FabricName               string                 `protobuf:"bytes,3,opt,name=fabricName,proto3" json:"fabricName,omitempty"`
	NodeNames                []string               `protobuf:"bytes,4,rep,name=nodeNames,proto3" json:"nodeNames,omitempty"`
	StatSubType              string                 `protobuf:"bytes,5,opt,name=statSubType,proto3" json:"statSubType,omitempty"` // Deprecated field from NI 6.0
	StatName                 string                 `protobuf:"bytes,6,opt,name=statName,proto3" json:"statName,omitempty"`       // Deprecated field from NI 6.0
	AnomalyType              string                 `protobuf:"bytes,7,opt,name=anomalyType,proto3" json:"anomalyType,omitempty"`
	Reason                   string                 `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
	Severity                 string                 `protobuf:"bytes,9,opt,name=severity,proto3" json:"severity,omitempty"`
	Category                 string                 `protobuf:"bytes,10,opt,name=category,proto3" json:"category,omitempty"`
	EntityName               string                 `protobuf:"bytes,11,opt,name=entityName,proto3" json:"entityName,omitempty"`
	StreamingAnomaly         bool                   `protobuf:"varint,12,opt,name=streamingAnomaly,proto3" json:"streamingAnomaly,omitempty"`
	Cleared                  bool                   `protobuf:"varint,13,opt,name=cleared,proto3" json:"cleared,omitempty"`
	ClearTs                  string                 `protobuf:"bytes,14,opt,name=clearTs,proto3" json:"clearTs,omitempty"`
	MasterClearTs            string                 `protobuf:"bytes,15,opt,name=masterClearTs,proto3" json:"masterClearTs,omitempty"`
	CustomData               *CustomData            `protobuf:"bytes,16,opt,name=customData,proto3" json:"customData,omitempty"`
	AlertType                string                 `protobuf:"bytes,17,opt,name=alertType,proto3" json:"alertType,omitempty"`
	AlertId                  string                 `protobuf:"bytes,18,opt,name=alertId,proto3" json:"alertId,omitempty"`
	Title                    string                 `protobuf:"bytes,19,opt,name=title,proto3" json:"title,omitempty"`
	Recommendation           bool                   `protobuf:"varint,20,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	Impact                   bool                   `protobuf:"varint,21,opt,name=impact,proto3" json:"impact,omitempty"`
	ExtendStreamingAnomaly   bool                   `protobuf:"varint,22,opt,name=extendStreamingAnomaly,proto3" json:"extendStreamingAnomaly,omitempty"`
	AnomalyId                string                 `protobuf:"bytes,23,opt,name=anomalyId,proto3" json:"anomalyId,omitempty"`
	NewAlert                 bool                   `protobuf:"varint,24,opt,name=newAlert,proto3" json:"newAlert,omitempty"` // Deprecated field from NI 6.0
	EpochStartTs             int64                  `protobuf:"varint,25,opt,name=epochStartTs,proto3" json:"epochStartTs,omitempty"`
	EpochEndTs               int64                  `protobuf:"varint,26,opt,name=epochEndTs,proto3" json:"epochEndTs,omitempty"`
	MnemonicTitle            string                 `protobuf:"bytes,27,opt,name=mnemonicTitle,proto3" json:"mnemonicTitle,omitempty"`
	MnemonicDescription      string                 `protobuf:"bytes,28,opt,name=mnemonicDescription,proto3" json:"mnemonicDescription,omitempty"`
	MnemonicNum              int32                  `protobuf:"varint,29,opt,name=mnemonicNum,proto3" json:"mnemonicNum,omitempty"`
	EntityNameList           []*EntityNameList      `protobuf:"bytes,30,rep,name=entityNameList,proto3" json:"entityNameList,omitempty"`
	TargetIndex              string                 `protobuf:"bytes,31,opt,name=targetIndex,proto3" json:"targetIndex,omitempty"`
	ParentAnomalyIdList      []string               `protobuf:"bytes,32,rep,name=parentAnomalyIdList,proto3" json:"parentAnomalyIdList,omitempty"`
	ResourceName             string                 `protobuf:"bytes,33,opt,name=resourceName,proto3" json:"resourceName,omitempty"`
	ResourceType             string                 `protobuf:"bytes,34,opt,name=resourceType,proto3" json:"resourceType,omitempty"`
	Acknowledged             bool                   `protobuf:"varint,35,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	AckTs                    string                 `protobuf:"bytes,36,opt,name=ackTs,proto3" json:"ackTs,omitempty"`
	UpdateAlert              bool                   `protobuf:"varint,37,opt,name=updateAlert,proto3" json:"updateAlert,omitempty"`
	VerificationStatus       string                 `protobuf:"bytes,38,opt,name=verificationStatus,proto3" json:"verificationStatus,omitempty"`
	Assignee                 string                 `protobuf:"bytes,39,opt,name=assignee,proto3" json:"assignee,omitempty"`
	Tags                     []string               `protobuf:"bytes,40,rep,name=tags,proto3" json:"tags,omitempty"`
	Comment                  string                 `protobuf:"bytes,41,opt,name=comment,proto3" json:"comment,omitempty"`
	Vendor                   string                 `protobuf:"bytes,42,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Offline                  bool                   `protobuf:"varint,43,opt,name=offline,proto3" json:"offline,omitempty"`
	AutoAck                  bool                   `protobuf:"varint,44,opt,name=autoAck,proto3" json:"autoAck,omitempty"`
	ManualAck                string                 `protobuf:"bytes,45,opt,name=manualAck,proto3" json:"manualAck,omitempty"`
	ActiveTs                 string                 `protobuf:"bytes,46,opt,name=activeTs,proto3" json:"activeTs,omitempty"`
	EpochActiveTs            int64                  `protobuf:"varint,47,opt,name=epochActiveTs,proto3" json:"epochActiveTs,omitempty"`
	HashKey                  int64                  `protobuf:"varint,48,opt,name=hashKey,proto3" json:"hashKey,omitempty"`
	UpdateAcknowledged       bool                   `protobuf:"varint,49,opt,name=updateAcknowledged,proto3" json:"updateAcknowledged,omitempty"`
	UpdateTags               bool                   `protobuf:"varint,50,opt,name=updateTags,proto3" json:"updateTags,omitempty"`
	UpdateVerificationStatus bool                   `protobuf:"varint,51,opt,name=updateVerificationStatus,proto3" json:"updateVerificationStatus,omitempty"`
	UpdateAssignee           bool                   `protobuf:"varint,52,opt,name=updateAssignee,proto3" json:"updateAssignee,omitempty"`
	UpdateComment            bool                   `protobuf:"varint,53,opt,name=updateComment,proto3" json:"updateComment,omitempty"`
	CheckCodes               []string               `protobuf:"bytes,54,rep,name=checkCodes,proto3" json:"checkCodes,omitempty"`
	MultiFabricAlert         bool                   `protobuf:"varint,55,opt,name=multiFabricAlert,proto3" json:"multiFabricAlert,omitempty"`
	AffectedObjects          []*AnomalyObjectsList  `protobuf:"bytes,56,rep,name=affectedObjects,proto3" json:"affectedObjects,omitempty"`
	EventSignature           string                 `protobuf:"bytes,57,opt,name=eventSignature,proto3" json:"eventSignature,omitempty"`
	MsoPrimaryKey            string                 `protobuf:"bytes,58,opt,name=msoPrimaryKey,proto3" json:"msoPrimaryKey,omitempty"`
	RuleType                 string                 `protobuf:"bytes,59,opt,name=ruleType,proto3" json:"ruleType,omitempty"`
	RuleId                   string                 `protobuf:"bytes,60,opt,name=ruleId,proto3" json:"ruleId,omitempty"`
	RuleName                 string                 `protobuf:"bytes,61,opt,name=ruleName,proto3" json:"ruleName,omitempty"`
	ImpactStr                string                 `protobuf:"bytes,62,opt,name=impactStr,proto3" json:"impactStr,omitempty"`
	RecommendationStr        string                 `protobuf:"bytes,63,opt,name=recommendationStr,proto3" json:"recommendationStr,omitempty"`
	WhatsTriggeredStr        string                 `protobuf:"bytes,64,opt,name=whatsTriggeredStr,proto3" json:"whatsTriggeredStr,omitempty"`
	AppVersion               string                 `protobuf:"bytes,65,opt,name=appVersion,proto3" json:"appVersion,omitempty"`
	AnalysisTsList           []string               `protobuf:"bytes,66,rep,name=analysisTsList,proto3" json:"analysisTsList,omitempty"`
	IsCorrelated             bool                   `protobuf:"varint,67,opt,name=isCorrelated,proto3" json:"isCorrelated,omitempty"`
	IsRoot                   bool                   `protobuf:"varint,68,opt,name=isRoot,proto3" json:"isRoot,omitempty"`
	ImpactCount              int32                  `protobuf:"varint,69,opt,name=impactCount,proto3" json:"impactCount,omitempty"`
	Sender                   string                 `protobuf:"bytes,70,opt,name=sender,proto3" json:"sender,omitempty"`
	AnomalySource            string                 `protobuf:"bytes,71,opt,name=anomalySource,proto3" json:"anomalySource,omitempty"`
	Device                   string                 `protobuf:"bytes,72,opt,name=device,proto3" json:"device,omitempty"`
	SwitchId                 string                 `protobuf:"bytes,73,opt,name=switchId,proto3" json:"switchId,omitempty"`
	PolicyName               string                 `protobuf:"bytes,74,opt,name=policyName,proto3" json:"policyName,omitempty"`
	CustomSourceData         string                 `protobuf:"bytes,75,opt,name=customSourceData,proto3" json:"customSourceData,omitempty"`
	ManualClear              bool                   `protobuf:"varint,76,opt,name=manualClear,proto3" json:"manualClear,omitempty"`
	UpdateClear              bool                   `protobuf:"varint,77,opt,name=updateClear,proto3" json:"updateClear,omitempty"`
	UpdateDelete             bool                   `protobuf:"varint,78,opt,name=updateDelete,proto3" json:"updateDelete,omitempty"`
	NewAnomaly               bool                   `protobuf:"varint,79,opt,name=newAnomaly,proto3" json:"newAnomaly,omitempty"`
	CustomRecommendation     bool                   `protobuf:"varint,80,opt,name=customRecommendation,proto3" json:"customRecommendation,omitempty"`
	CacheKey                 string                 `protobuf:"bytes,81,opt,name=cacheKey,proto3" json:"cacheKey,omitempty"`
	CompositeKey             string                 `protobuf:"bytes,82,opt,name=compositeKey,proto3" json:"compositeKey,omitempty"`
	Remediation              []*Remediation         `protobuf:"bytes,83,rep,name=remediation,proto3" json:"remediation,omitempty"`
	ServiceName              string                 `protobuf:"bytes,84,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	ClusterName              string                 `protobuf:"bytes,85,opt,name=clusterName,proto3" json:"clusterName,omitempty"`
	IsRuleCustomReco         bool                   `protobuf:"varint,86,opt,name=isRuleCustomReco,proto3" json:"isRuleCustomReco,omitempty"`
	RuleCustomRecoStr        []string               `protobuf:"bytes,87,rep,name=ruleCustomRecoStr,proto3" json:"ruleCustomRecoStr,omitempty"`
	RuleCustomRecoAction     string                 `protobuf:"bytes,88,opt,name=ruleCustomRecoAction,proto3" json:"ruleCustomRecoAction,omitempty"`
	AlertRuleName            string                 `protobuf:"bytes,89,opt,name=alertRuleName,proto3" json:"alertRuleName,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_alert_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{14}
}

func (x *Alert) GetStartTs() string {
	if x != nil {
		return x.StartTs
	}
	return ""
}

func (x *Alert) GetEndTs() string {
	if x != nil {
		return x.EndTs
	}
	return ""
}

func (x *Alert) GetFabricName() string {
	if x != nil {
		return x.FabricName
	}
	return ""
}

func (x *Alert) GetNodeNames() []string {
	if x != nil {
		return x.NodeNames
	}
	return nil
}

func (x *Alert) GetStatSubType() string {
	if x != nil {
		return x.StatSubType
	}
	return ""
}

func (x *Alert) GetStatName() string {
	if x != nil {
		return x.StatName
	}
	return ""
}

func (x *Alert) GetAnomalyType() string {
	if x != nil {
		return x.AnomalyType
	}
	return ""
}

func (x *Alert) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Alert) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Alert) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Alert) GetEntityName() string {
	if x != nil {
		return x.EntityName
	}
	return ""
}

func (x *Alert) GetStreamingAnomaly() bool {
	if x != nil {
		return x.StreamingAnomaly
	}
	return false
}

func (x *Alert) GetCleared() bool {
	if x != nil {
		return x.Cleared
	}
	return false
}

func (x *Alert) GetClearTs() string {
	if x != nil {
		return x.ClearTs
	}
	return ""
}

func (x *Alert) GetMasterClearTs() string {
	if x != nil {
		return x.MasterClearTs
	}
	return ""
}

func (x *Alert) GetCustomData() *CustomData {
	if x != nil {
		return x.CustomData
	}
	return nil
}

func (x *Alert) GetAlertType() string {
	if x != nil {
		return x.AlertType
	}
	return ""
}

func (x *Alert) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

func (x *Alert) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Alert) GetRecommendation() bool {
	if x != nil {
		return x.Recommendation
	}
	return false
}

func (x *Alert) GetImpact() bool {
	if x != nil {
		return x.Impact
	}
	return false
}

func (x *Alert) GetExtendStreamingAnomaly() bool {
	if x != nil {
		return x.ExtendStreamingAnomaly
	}
	return false
}

func (x *Alert) GetAnomalyId() string {
	if x != nil {
		return x.AnomalyId
	}
	return ""
}

func (x *Alert) GetNewAlert() bool {
	if x != nil {
		return x.NewAlert
	}
	return false
}

func (x *Alert) GetEpochStartTs() int64 {
	if x != nil {
		return x.EpochStartTs
	}
	return 0
}

func (x *Alert) GetEpochEndTs() int64 {
	if x != nil {
		return x.EpochEndTs
	}
	return 0
}

func (x *Alert) GetMnemonicTitle() string {
	if x != nil {
		return x.MnemonicTitle
	}
	return ""
}

func (x *Alert) GetMnemonicDescription() string {
	if x != nil {
		return x.MnemonicDescription
	}
	return ""
}

func (x *Alert) GetMnemonicNum() int32 {
	if x != nil {
		return x.MnemonicNum
	}
	return 0
}

func (x *Alert) GetEntityNameList() []*EntityNameList {
	if x != nil {
		return x.EntityNameList
	}
	return nil
}

func (x *Alert) GetTargetIndex() string {
	if x != nil {
		return x.TargetIndex
	}
	return ""
}

func (x *Alert) GetParentAnomalyIdList() []string {
	if x != nil {
		return x.ParentAnomalyIdList
	}
	return nil
}

func (x *Alert) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *Alert) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *Alert) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *Alert) GetAckTs() string {
	if x != nil {
		return x.AckTs
	}
	return ""
}

func (x *Alert) GetUpdateAlert() bool {
	if x != nil {
		return x.UpdateAlert
	}
	return false
}

func (x *Alert) GetVerificationStatus() string {
	if x != nil {
		return x.VerificationStatus
	}
	return ""
}

func (x *Alert) GetAssignee() string {
	if x != nil {
		return x.Assignee
	}
	return ""
}

func (x *Alert) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Alert) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Alert) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *Alert) GetOffline() bool {
	if x != nil {
		return x.Offline
	}
	return false
}

func (x *Alert) GetAutoAck() bool {
	if x != nil {
		return x.AutoAck
	}
	return false
}

func (x *Alert) GetManualAck() string {
	if x != nil {
		return x.ManualAck
	}
	return ""
}

func (x *Alert) GetActiveTs() string {
	if x != nil {
		return x.ActiveTs
	}
	return ""
}

func (x *Alert) GetEpochActiveTs() int64 {
	if x != nil {
		return x.EpochActiveTs
	}
	return 0
}

func (x *Alert) GetHashKey() int64 {
	if x != nil {
		return x.HashKey
	}
	return 0
}

func (x *Alert) GetUpdateAcknowledged() bool {
	if x != nil {
		return x.UpdateAcknowledged
	}
	return false
}

func (x *Alert) GetUpdateTags() bool {
	if x != nil {
		return x.UpdateTags
	}
	return false
}

func (x *Alert) GetUpdateVerificationStatus() bool {
	if x != nil {
		return x.UpdateVerificationStatus
	}
	return false
}

func (x *Alert) GetUpdateAssignee() bool {
	if x != nil {
		return x.UpdateAssignee
	}
	return false
}

func (x *Alert) GetUpdateComment() bool {
	if x != nil {
		return x.UpdateComment
	}
	return false
}

func (x *Alert) GetCheckCodes() []string {
	if x != nil {
		return x.CheckCodes
	}
	return nil
}

func (x *Alert) GetMultiFabricAlert() bool {
	if x != nil {
		return x.MultiFabricAlert
	}
	return false
}

func (x *Alert) GetAffectedObjects() []*AnomalyObjectsList {
	if x != nil {
		return x.AffectedObjects
	}
	return nil
}

func (x *Alert) GetEventSignature() string {
	if x != nil {
		return x.EventSignature
	}
	return ""
}

func (x *Alert) GetMsoPrimaryKey() string {
	if x != nil {
		return x.MsoPrimaryKey
	}
	return ""
}

func (x *Alert) GetRuleType() string {
	if x != nil {
		return x.RuleType
	}
	return ""
}

func (x *Alert) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *Alert) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *Alert) GetImpactStr() string {
	if x != nil {
		return x.ImpactStr
	}
	return ""
}

func (x *Alert) GetRecommendationStr() string {
	if x != nil {
		return x.RecommendationStr
	}
	return ""
}

func (x *Alert) GetWhatsTriggeredStr() string {
	if x != nil {
		return x.WhatsTriggeredStr
	}
	return ""
}

func (x *Alert) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *Alert) GetAnalysisTsList() []string {
	if x != nil {
		return x.AnalysisTsList
	}
	return nil
}

func (x *Alert) GetIsCorrelated() bool {
	if x != nil {
		return x.IsCorrelated
	}
	return false
}

func (x *Alert) GetIsRoot() bool {
	if x != nil {
		return x.IsRoot
	}
	return false
}

func (x *Alert) GetImpactCount() int32 {
	if x != nil {
		return x.ImpactCount
	}
	return 0
}

func (x *Alert) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Alert) GetAnomalySource() string {
	if x != nil {
		return x.AnomalySource
	}
	return ""
}

func (x *Alert) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Alert) GetSwitchId() string {
	if x != nil {
		return x.SwitchId
	}
	return ""
}

func (x *Alert) GetPolicyName() string {
	if x != nil {
		return x.PolicyName
	}
	return ""
}

func (x *Alert) GetCustomSourceData() string {
	if x != nil {
		return x.CustomSourceData
	}
	return ""
}

func (x *Alert) GetManualClear() bool {
	if x != nil {
		return x.ManualClear
	}
	return false
}

func (x *Alert) GetUpdateClear() bool {
	if x != nil {
		return x.UpdateClear
	}
	return false
}

func (x *Alert) GetUpdateDelete() bool {
	if x != nil {
		return x.UpdateDelete
	}
	return false
}

func (x *Alert) GetNewAnomaly() bool {
	if x != nil {
		return x.NewAnomaly
	}
	return false
}

func (x *Alert) GetCustomRecommendation() bool {
	if x != nil {
		return x.CustomRecommendation
	}
	return false
}

func (x *Alert) GetCacheKey() string {
	if x != nil {
		return x.CacheKey
	}
	return ""
}

func (x *Alert) GetCompositeKey() string {
	if x != nil {
		return x.CompositeKey
	}
	return ""
}

func (x *Alert) GetRemediation() []*Remediation {
	if x != nil {
		return x.Remediation
	}
	return nil
}

func (x *Alert) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Alert) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *Alert) GetIsRuleCustomReco() bool {
	if x != nil {
		return x.IsRuleCustomReco
	}
	return false
}

func (x *Alert) GetRuleCustomRecoStr() []string {
	if x != nil {
		return x.RuleCustomRecoStr
	}
	return nil
}

func (x *Alert) GetRuleCustomRecoAction() string {
	if x != nil {
		return x.RuleCustomRecoAction
	}
	return ""
}

func (x *Alert) GetAlertRuleName() string {
	if x != nil {
		return x.AlertRuleName
	}
	return ""
}

type Remediation struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Desc               string                 `protobuf:"bytes,1,opt,name=desc,proto3" json:"desc,omitempty"`
	Method             string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	RemediationPayload string                 `protobuf:"bytes,3,opt,name=remediationPayload,proto3" json:"remediationPayload,omitempty"`
	Uri                string                 `protobuf:"bytes,4,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Remediation) Reset() {
	*x = Remediation{}
	mi := &file_alert_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Remediation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Remediation) ProtoMessage() {}

func (x *Remediation) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Remediation.ProtoReflect.Descriptor instead.
func (*Remediation) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{15}
}

func (x *Remediation) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Remediation) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Remediation) GetRemediationPayload() string {
	if x != nil {
		return x.RemediationPayload
	}
	return ""
}

func (x *Remediation) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type AlertStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertObject   []*Alert               `protobuf:"bytes,1,rep,name=alertObject,proto3" json:"alertObject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertStream) Reset() {
	*x = AlertStream{}
	mi := &file_alert_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertStream) ProtoMessage() {}

func (x *AlertStream) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertStream.ProtoReflect.Descriptor instead.
func (*AlertStream) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{16}
}

func (x *AlertStream) GetAlertObject() []*Alert {
	if x != nil {
		return x.AlertObject
	}
	return nil
}

var File_alert_proto protoreflect.FileDescriptor

const file_alert_proto_rawDesc = "" +
	"\n" +
	"\valert.proto\x12\x05alert\"\x96\x01\n" +
	"\x06Params\x12\x1e\n" +
	"\n" +
	"fabricName\x18\x01 \x01(\tR\n" +
	"fabricName\x12\x1a\n" +
	"\bnodeName\x18\x02 \x01(\tR\bnodeName\x12 \n" +
	"\vanomalyType\x18\x03 \x01(\tR\vanomalyType\x12\x18\n" +
	"\astartTs\x18\x04 \x01(\tR\astartTs\x12\x14\n" +
	"\x05endTs\x18\x05 \x01(\tR\x05endTs\"k\n" +
	"\n" +
	"AffectedEp\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12$\n" +
	"\rendpointCount\x18\x02 \x01(\x05R\rendpointCount\x12%\n" +
	"\x06params\x18\x03 \x01(\v2\r.alert.ParamsR\x06params\"\x97\x01\n" +
	"\tAdjacency\x12&\n" +
	"\x0epeerDeviceName\x18\x01 \x01(\tR\x0epeerDeviceName\x12,\n" +
	"\x11peerInterfaceName\x18\x02 \x01(\tR\x11peerInterfaceName\x12\x14\n" +
	"\x05modTs\x18\x03 \x01(\tR\x05modTs\x12\x1e\n" +
	"\n" +
	"fabricName\x18\x04 \x01(\tR\n" +
	"fabricName\"\xf3\x01\n" +
	"\aVpcNode\x12\x1a\n" +
	"\bnodeName\x18\x01 \x01(\tR\bnodeName\x12\x1c\n" +
	"\tinterface\x18\x02 \x01(\tR\tinterface\x12\x12\n" +
	"\x04pcId\x18\x03 \x01(\tR\x04pcId\x12\x1c\n" +
	"\tvpcOperSt\x18\x04 \x01(\tR\tvpcOperSt\x12(\n" +
	"\x0fpcOperStateQual\x18\x05 \x01(\tR\x0fpcOperStateQual\x12$\n" +
	"\rinterfaceType\x18\x06 \x01(\tR\rinterfaceType\x12,\n" +
	"\x11interfaceUniqueId\x18\a \x01(\tR\x11interfaceUniqueId\"8\n" +
	"\x02Pc\x122\n" +
	"\x14configuredMemberList\x18\x01 \x03(\tR\x14configuredMemberList\"M\n" +
	"\x03Vpc\x12\x1a\n" +
	"\bdomainId\x18\x01 \x01(\tR\bdomainId\x12*\n" +
	"\bnodeList\x18\x02 \x03(\v2\x0e.alert.VpcNodeR\bnodeList\"\x8d\x01\n" +
	"\x03Bgp\x12\x16\n" +
	"\x06connIf\x18\x01 \x01(\tR\x06connIf\x12\x18\n" +
	"\abgpType\x18\x02 \x01(\tR\abgpType\x12*\n" +
	"\x10prefixChangeType\x18\x03 \x01(\tR\x10prefixChangeType\x12\x16\n" +
	"\x06peerIp\x18\x04 \x01(\tR\x06peerIp\x12\x10\n" +
	"\x03vrf\x18\x05 \x01(\tR\x03vrf\"r\n" +
	"\x04Ospf\x120\n" +
	"\x13interfaceNameFromDN\x18\x01 \x01(\tR\x13interfaceNameFromDN\x12 \n" +
	"\vderivedIntf\x18\x02 \x01(\tR\vderivedIntf\x12\x16\n" +
	"\x06peerIp\x18\x03 \x01(\tR\x06peerIp\"7\n" +
	"\x03Svi\x120\n" +
	"\x13associatedInterface\x18\x01 \x01(\tR\x13associatedInterface\"5\n" +
	"\vCustomEvent\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\"O\n" +
	"\tApicFault\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12 \n" +
	"\vconfigQuals\x18\x02 \x03(\tR\vconfigQuals\"\x95\a\n" +
	"\n" +
	"CustomData\x12&\n" +
	"\x0econtrollerName\x18\x01 \x01(\tR\x0econtrollerName\x12 \n" +
	"\vaccountName\x18\x02 \x01(\tR\vaccountName\x12(\n" +
	"\x0fapplicationName\x18\x03 \x01(\tR\x0fapplicationName\x12\x1a\n" +
	"\btierName\x18\x04 \x01(\tR\btierName\x12\x1a\n" +
	"\bnodeName\x18\x05 \x01(\tR\bnodeName\x12&\n" +
	"\x0ehealthRuleName\x18\x06 \x01(\tR\x0ehealthRuleName\x12\x16\n" +
	"\x06vrfDip\x18\a \x01(\tR\x06vrfDip\x121\n" +
	"\n" +
	"affectedEp\x18\b \x01(\v2\x11.alert.AffectedEpR\n" +
	"affectedEp\x12\x1c\n" +
	"\tendpoints\x18\t \x03(\tR\tendpoints\x12\x1a\n" +
	"\bhostName\x18\n" +
	" \x01(\tR\bhostName\x12\x16\n" +
	"\x06vmName\x18\v \x01(\tR\x06vmName\x12 \n" +
	"\vnetworkName\x18\f \x01(\tR\vnetworkName\x12\x16\n" +
	"\x06dsName\x18\r \x01(\tR\x06dsName\x12\x1e\n" +
	"\n" +
	"deviceName\x18\x0e \x01(\tR\n" +
	"deviceName\x12\x1c\n" +
	"\tmoveCount\x18\x0f \x01(\x05R\tmoveCount\x12\x1e\n" +
	"\n" +
	"interfaces\x18\x10 \x01(\tR\n" +
	"interfaces\x12*\n" +
	"\x06events\x18\x11 \x03(\v2\x12.alert.CustomEventR\x06events\x12.\n" +
	"\tadjacency\x18\x12 \x01(\v2\x10.alert.AdjacencyR\tadjacency\x12\x1c\n" +
	"\x03vpc\x18\x13 \x01(\v2\n" +
	".alert.VpcR\x03vpc\x12\x19\n" +
	"\x02pc\x18\x14 \x01(\v2\t.alert.PcR\x02pc\x12\x1c\n" +
	"\x03bgp\x18\x15 \x01(\v2\n" +
	".alert.BgpR\x03bgp\x12\x12\n" +
	"\x04pcId\x18\x16 \x01(\tR\x04pcId\x12\x1f\n" +
	"\x04ospf\x18\x17 \x01(\v2\v.alert.OspfR\x04ospf\x12\x1c\n" +
	"\x03svi\x18\x18 \x01(\v2\n" +
	".alert.SviR\x03svi\x12\x18\n" +
	"\arcaData\x18\x19 \x01(\tR\arcaData\x12.\n" +
	"\tapicFault\x18\x1a \x01(\v2\x10.alert.ApicFaultR\tapicFault\x12.\n" +
	"\x12impactResourceType\x18\x1b \x01(\tR\x12impactResourceType\"R\n" +
	"\x0eEntityNameList\x12\x1e\n" +
	"\n" +
	"objectType\x18\x01 \x01(\tR\n" +
	"objectType\x12 \n" +
	"\vobjectValue\x18\x02 \x03(\tR\vobjectValue\"\x98\x01\n" +
	"\x12AnomalyObjectsList\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"identifier\x18\x02 \x01(\tR\n" +
	"identifier\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1c\n" +
	"\tisPrimary\x18\x04 \x01(\bR\tisPrimary\x12\x1c\n" +
	"\tisHealthy\x18\x05 \x01(\bR\tisHealthy\"\xc4\x18\n" +
	"\x05Alert\x12\x18\n" +
	"\astartTs\x18\x01 \x01(\tR\astartTs\x12\x14\n" +
	"\x05endTs\x18\x02 \x01(\tR\x05endTs\x12\x1e\n" +
	"\n" +
	"fabricName\x18\x03 \x01(\tR\n" +
	"fabricName\x12\x1c\n" +
	"\tnodeNames\x18\x04 \x03(\tR\tnodeNames\x12 \n" +
	"\vstatSubType\x18\x05 \x01(\tR\vstatSubType\x12\x1a\n" +
	"\bstatName\x18\x06 \x01(\tR\bstatName\x12 \n" +
	"\vanomalyType\x18\a \x01(\tR\vanomalyType\x12\x16\n" +
	"\x06reason\x18\b \x01(\tR\x06reason\x12\x1a\n" +
	"\bseverity\x18\t \x01(\tR\bseverity\x12\x1a\n" +
	"\bcategory\x18\n" +
	" \x01(\tR\bcategory\x12\x1e\n" +
	"\n" +
	"entityName\x18\v \x01(\tR\n" +
	"entityName\x12*\n" +
	"\x10streamingAnomaly\x18\f \x01(\bR\x10streamingAnomaly\x12\x18\n" +
	"\acleared\x18\r \x01(\bR\acleared\x12\x18\n" +
	"\aclearTs\x18\x0e \x01(\tR\aclearTs\x12$\n" +
	"\rmasterClearTs\x18\x0f \x01(\tR\rmasterClearTs\x121\n" +
	"\n" +
	"customData\x18\x10 \x01(\v2\x11.alert.CustomDataR\n" +
	"customData\x12\x1c\n" +
	"\talertType\x18\x11 \x01(\tR\talertType\x12\x18\n" +
	"\aalertId\x18\x12 \x01(\tR\aalertId\x12\x14\n" +
	"\x05title\x18\x13 \x01(\tR\x05title\x12&\n" +
	"\x0erecommendation\x18\x14 \x01(\bR\x0erecommendation\x12\x16\n" +
	"\x06impact\x18\x15 \x01(\bR\x06impact\x126\n" +
	"\x16extendStreamingAnomaly\x18\x16 \x01(\bR\x16extendStreamingAnomaly\x12\x1c\n" +
	"\tanomalyId\x18\x17 \x01(\tR\tanomalyId\x12\x1a\n" +
	"\bnewAlert\x18\x18 \x01(\bR\bnewAlert\x12\"\n" +
	"\fepochStartTs\x18\x19 \x01(\x03R\fepochStartTs\x12\x1e\n" +
	"\n" +
	"epochEndTs\x18\x1a \x01(\x03R\n" +
	"epochEndTs\x12$\n" +
	"\rmnemonicTitle\x18\x1b \x01(\tR\rmnemonicTitle\x120\n" +
	"\x13mnemonicDescription\x18\x1c \x01(\tR\x13mnemonicDescription\x12 \n" +
	"\vmnemonicNum\x18\x1d \x01(\x05R\vmnemonicNum\x12=\n" +
	"\x0eentityNameList\x18\x1e \x03(\v2\x15.alert.EntityNameListR\x0eentityNameList\x12 \n" +
	"\vtargetIndex\x18\x1f \x01(\tR\vtargetIndex\x120\n" +
	"\x13parentAnomalyIdList\x18  \x03(\tR\x13parentAnomalyIdList\x12\"\n" +
	"\fresourceName\x18! \x01(\tR\fresourceName\x12\"\n" +
	"\fresourceType\x18\" \x01(\tR\fresourceType\x12\"\n" +
	"\facknowledged\x18# \x01(\bR\facknowledged\x12\x14\n" +
	"\x05ackTs\x18$ \x01(\tR\x05ackTs\x12 \n" +
	"\vupdateAlert\x18% \x01(\bR\vupdateAlert\x12.\n" +
	"\x12verificationStatus\x18& \x01(\tR\x12verificationStatus\x12\x1a\n" +
	"\bassignee\x18' \x01(\tR\bassignee\x12\x12\n" +
	"\x04tags\x18( \x03(\tR\x04tags\x12\x18\n" +
	"\acomment\x18) \x01(\tR\acomment\x12\x16\n" +
	"\x06vendor\x18* \x01(\tR\x06vendor\x12\x18\n" +
	"\aoffline\x18+ \x01(\bR\aoffline\x12\x18\n" +
	"\aautoAck\x18, \x01(\bR\aautoAck\x12\x1c\n" +
	"\tmanualAck\x18- \x01(\tR\tmanualAck\x12\x1a\n" +
	"\bactiveTs\x18. \x01(\tR\bactiveTs\x12$\n" +
	"\repochActiveTs\x18/ \x01(\x03R\repochActiveTs\x12\x18\n" +
	"\ahashKey\x180 \x01(\x03R\ahashKey\x12.\n" +
	"\x12updateAcknowledged\x181 \x01(\bR\x12updateAcknowledged\x12\x1e\n" +
	"\n" +
	"updateTags\x182 \x01(\bR\n" +
	"updateTags\x12:\n" +
	"\x18updateVerificationStatus\x183 \x01(\bR\x18updateVerificationStatus\x12&\n" +
	"\x0eupdateAssignee\x184 \x01(\bR\x0eupdateAssignee\x12$\n" +
	"\rupdateComment\x185 \x01(\bR\rupdateComment\x12\x1e\n" +
	"\n" +
	"checkCodes\x186 \x03(\tR\n" +
	"checkCodes\x12*\n" +
	"\x10multiFabricAlert\x187 \x01(\bR\x10multiFabricAlert\x12C\n" +
	"\x0faffectedObjects\x188 \x03(\v2\x19.alert.AnomalyObjectsListR\x0faffectedObjects\x12&\n" +
	"\x0eeventSignature\x189 \x01(\tR\x0eeventSignature\x12$\n" +
	"\rmsoPrimaryKey\x18: \x01(\tR\rmsoPrimaryKey\x12\x1a\n" +
	"\bruleType\x18; \x01(\tR\bruleType\x12\x16\n" +
	"\x06ruleId\x18< \x01(\tR\x06ruleId\x12\x1a\n" +
	"\bruleName\x18= \x01(\tR\bruleName\x12\x1c\n" +
	"\timpactStr\x18> \x01(\tR\timpactStr\x12,\n" +
	"\x11recommendationStr\x18? \x01(\tR\x11recommendationStr\x12,\n" +
	"\x11whatsTriggeredStr\x18@ \x01(\tR\x11whatsTriggeredStr\x12\x1e\n" +
	"\n" +
	"appVersion\x18A \x01(\tR\n" +
	"appVersion\x12&\n" +
	"\x0eanalysisTsList\x18B \x03(\tR\x0eanalysisTsList\x12\"\n" +
	"\fisCorrelated\x18C \x01(\bR\fisCorrelated\x12\x16\n" +
	"\x06isRoot\x18D \x01(\bR\x06isRoot\x12 \n" +
	"\vimpactCount\x18E \x01(\x05R\vimpactCount\x12\x16\n" +
	"\x06sender\x18F \x01(\tR\x06sender\x12$\n" +
	"\ranomalySource\x18G \x01(\tR\ranomalySource\x12\x16\n" +
	"\x06device\x18H \x01(\tR\x06device\x12\x1a\n" +
	"\bswitchId\x18I \x01(\tR\bswitchId\x12\x1e\n" +
	"\n" +
	"policyName\x18J \x01(\tR\n" +
	"policyName\x12*\n" +
	"\x10customSourceData\x18K \x01(\tR\x10customSourceData\x12 \n" +
	"\vmanualClear\x18L \x01(\bR\vmanualClear\x12 \n" +
	"\vupdateClear\x18M \x01(\bR\vupdateClear\x12\"\n" +
	"\fupdateDelete\x18N \x01(\bR\fupdateDelete\x12\x1e\n" +
	"\n" +
	"newAnomaly\x18O \x01(\bR\n" +
	"newAnomaly\x122\n" +
	"\x14customRecommendation\x18P \x01(\bR\x14customRecommendation\x12\x1a\n" +
	"\bcacheKey\x18Q \x01(\tR\bcacheKey\x12\"\n" +
	"\fcompositeKey\x18R \x01(\tR\fcompositeKey\x124\n" +
	"\vremediation\x18S \x03(\v2\x12.alert.RemediationR\vremediation\x12 \n" +
	"\vserviceName\x18T \x01(\tR\vserviceName\x12 \n" +
	"\vclusterName\x18U \x01(\tR\vclusterName\x12*\n" +
	"\x10isRuleCustomReco\x18V \x01(\bR\x10isRuleCustomReco\x12,\n" +
	"\x11ruleCustomRecoStr\x18W \x03(\tR\x11ruleCustomRecoStr\x122\n" +
	"\x14ruleCustomRecoAction\x18X \x01(\tR\x14ruleCustomRecoAction\x12$\n" +
	"\ralertRuleName\x18Y \x01(\tR\ralertRuleName\"{\n" +
	"\vRemediation\x12\x12\n" +
	"\x04desc\x18\x01 \x01(\tR\x04desc\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12.\n" +
	"\x12remediationPayload\x18\x03 \x01(\tR\x12remediationPayload\x12\x10\n" +
	"\x03uri\x18\x04 \x01(\tR\x03uri\"=\n" +
	"\vAlertStream\x12.\n" +
	"\valertObject\x18\x01 \x03(\v2\f.alert.AlertR\valertObjectB2\n" +
	"\x17com.cisco.aci.telemetryB\vAlertProtosH\x03Z\b./;alertb\x06proto3"

var (
	file_alert_proto_rawDescOnce sync.Once
	file_alert_proto_rawDescData []byte
)

func file_alert_proto_rawDescGZIP() []byte {
	file_alert_proto_rawDescOnce.Do(func() {
		file_alert_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alert_proto_rawDesc), len(file_alert_proto_rawDesc)))
	})
	return file_alert_proto_rawDescData
}

var file_alert_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_alert_proto_goTypes = []any{
	(*Params)(nil),             // 0: alert.Params
	(*AffectedEp)(nil),         // 1: alert.AffectedEp
	(*Adjacency)(nil),          // 2: alert.Adjacency
	(*VpcNode)(nil),            // 3: alert.VpcNode
	(*Pc)(nil),                 // 4: alert.Pc
	(*Vpc)(nil),                // 5: alert.Vpc
	(*Bgp)(nil),                // 6: alert.Bgp
	(*Ospf)(nil),               // 7: alert.Ospf
	(*Svi)(nil),                // 8: alert.Svi
	(*CustomEvent)(nil),        // 9: alert.CustomEvent
	(*ApicFault)(nil),          // 10: alert.ApicFault
	(*CustomData)(nil),         // 11: alert.CustomData
	(*EntityNameList)(nil),     // 12: alert.EntityNameList
	(*AnomalyObjectsList)(nil), // 13: alert.AnomalyObjectsList
	(*Alert)(nil),              // 14: alert.Alert
	(*Remediation)(nil),        // 15: alert.Remediation
	(*AlertStream)(nil),        // 16: alert.AlertStream
}
var file_alert_proto_depIdxs = []int32{
	0,  // 0: alert.AffectedEp.params:type_name -> alert.Params
	3,  // 1: alert.Vpc.nodeList:type_name -> alert.VpcNode
	1,  // 2: alert.CustomData.affectedEp:type_name -> alert.AffectedEp
	9,  // 3: alert.CustomData.events:type_name -> alert.CustomEvent
	2,  // 4: alert.CustomData.adjacency:type_name -> alert.Adjacency
	5,  // 5: alert.CustomData.vpc:type_name -> alert.Vpc
	4,  // 6: alert.CustomData.pc:type_name -> alert.Pc
	6,  // 7: alert.CustomData.bgp:type_name -> alert.Bgp
	7,  // 8: alert.CustomData.ospf:type_name -> alert.Ospf
	8,  // 9: alert.CustomData.svi:type_name -> alert.Svi
	10, // 10: alert.CustomData.apicFault:type_name -> alert.ApicFault
	11, // 11: alert.Alert.customData:type_name -> alert.CustomData
	12, // 12: alert.Alert.entityNameList:type_name -> alert.EntityNameList
	13, // 13: alert.Alert.affectedObjects:type_name -> alert.AnomalyObjectsList
	15, // 14: alert.Alert.remediation:type_name -> alert.Remediation
	14, // 15: alert.AlertStream.alertObject:type_name -> alert.Alert
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_alert_proto_init() }
func file_alert_proto_init() {
	if File_alert_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alert_proto_rawDesc), len(file_alert_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alert_proto_goTypes,
		DependencyIndexes: file_alert_proto_depIdxs,
		MessageInfos:      file_alert_proto_msgTypes,
	}.Build()
	File_alert_proto = out.File
	file_alert_proto_goTypes = nil
	file_alert_proto_depIdxs = nil
}
